# Generated by Django 3.0.14 on 2022-04-09 17:43

from django.db import migrations
import form.fields


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code',
            field=form.fields.NonStrippingTextField(),
        ),
    ]
